In [5]:
import pandas as pd
df = pd.read_csv(r"F:\zizo\RTKCorrection\src\data\navigation\PostProcessed\ROVER_FullNavigation_parameters3.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   System                   24 non-null     object
 1   PRN                      24 non-null     int64
 2   Epoch (UTC)              24 non-null     object
 3   Clock Bias (s)           24 non-null     float64
 4   Clock Drift (s/s)        24 non-null     float64
 5   Clock Drift Rate (s/s²)  24 non-null     float64
 6   IODE                     24 non-null     float64
 7   Crs (m)                  24 non-null     float64
 8   Δn (rad/s)               24 non-null     float64
 9   M0 (rad)                 24 non-null     float64
 10  Cuc (rad)                24 non-null     float64
 11  Eccentricity             24 non-null     float64
 12  Cus (rad)                24 non-null     float64
 13  √A (m^0.5)               24 non-null     float64
 14  toe (s)                  24 non-null     float64
 15  Cic (rad)                24 non-null     float64
 16  Ω0 (rad)                 24 non-null     float64
 17  Cis (rad)                24 non-null     float64
 18  i0 (rad)                 24 non-null     float64
 19  Crc (m)                  24 non-null     float64
 20  ω (rad)                  24 non-null     float64
 21  Ω̇ (rad/s)               24 non-null     float64
 22  IDOT (rad/s)             24 non-null     float64
 23  Codes L2                 24 non-null     float64
 24  GPS Week                 24 non-null     float64
 25  L2P flag                 24 non-null     float64
 26  SV accuracy (m)          24 non-null     float64
 27  SV health                24 non-null     float64
 28  TGD (s)                  24 non-null     float64
 29  IODC                     24 non-null     float64
 30  toc (s)                  24 non-null     float64
 31  Fit interval (h)         24 non-null     float64
dtypes: float64(29), int64(1), object(2)
memory usage: 6.1+ KB

In [6]:
df.describe()

,PRN,Clock Bias (s),Clock Drift (s/s),Clock Drift Rate (s/s²),IODE,Crs (m),Δn (rad/s),M0 (rad),Cuc (rad),Eccentricity,...,IDOT (rad/s),Codes L2,GPS Week,L2P flag,SV accuracy (m),SV health,TGD (s),IODC,toc (s),Fit interval (h)
count,24.000000,24.000000,2.400000e+01,24.0,24.000000,24.000000,2.400000e+01,24.000000,2.400000e+01,24.000000,...,2.400000e+01,24.0,24.0,24.0,24.000000,24.0,2.400000e+01,24.000000,24.000000,24.0
mean,13.875000,0.000052,2.794801e-12,0.0,79.125000,-10.384115,4.690433e-09,0.735928,-5.849482e-07,0.010979,...,-1.509438e-10,1.0,2301.0,0.0,2.483333,0.0,-6.072999e-09,164.458333,278409.750000,4.0
std,8.502238,0.000352,7.028938e-12,0.0,61.433819,55.519299,2.628949e-10,1.572621,2.871135e-06,0.006897,...,2.392509e-10,0.0,0.0,0.0,0.282330,0.0,7.188437e-09,276.855162,2957.705945,0.0
min,2.000000,-0.000486,-9.094947e-12,0.0,7.000000,-61.906250,4.110528e-09,-2.680661,-3.496185e-06,0.002780,...,-4.114457e-10,1.0,2301.0,0.0,2.400000,0.0,-1.769513e-08,7.000000,274776.000000,4.0
25%,7.750000,-0.000167,-1.932676e-12,0.0,46.500000,-50.171875,4.492330e-09,0.201497,-2.598390e-06,0.003982,...,-3.135845e-10,1.0,2301.0,0.0,2.400000,0.0,-1.117587e-08,46.500000,274993.500000,4.0
50%,13.500000,0.000062,4.206413e-12,0.0,71.500000,-34.031250,4.766806e-09,1.231397,-1.795590e-06,0.010860,...,-2.514390e-10,1.0,2301.0,0.0,2.400000,0.0,-9.080395e-09,71.500000,279666.000000,4.0
75%,21.000000,0.000291,9.436008e-12,0.0,86.250000,2.406250,4.911455e-09,1.857288,6.193295e-08,0.014945,...,-1.000935e-10,1.0,2301.0,0.0,2.400000,0.0,1.396984e-09,86.250000,280903.500000,4.0
max,30.000000,0.000717,1.261924e-11,0.0,232.000000,97.375000,4.995565e-09,2.458535,5.023554e-06,0.025303,...,3.342996e-10,1.0,2301.0,0.0,3.400000,0.0,5.122274e-09,1000.000000,282486.000000,4.0

In [8]:
df['Epoch (UTC)'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 24 entries, 0 to 23
Series name: Epoch (UTC)
Non-Null Count  Dtype
--------------  -----
24 non-null     object
dtypes: object(1)
memory usage: 320.0+ bytes

In [6]:
import pandas as pd
import georinex as gr

# Read the observation file
obs_data = gr.load(r"F:\zizo\RTKCorrection\src\research\research_data\20240214-041908v2.obs")

# Display the data
df = obs_data.to_dataframe()
df.head()

                                       C1            L1        D1    S1
time                    sv
2024-02-14 04:19:28.004 G02           NaN           NaN       NaN   NaN
                        G04  2.183554e+07  8.941286e+07 -1607.162  48.0
                        G07  2.403299e+07  9.841108e+07  1402.741  43.0
                        G08  2.177553e+07  8.916716e+07   760.247  47.0
                        G09  2.159509e+07  8.842827e+07   421.945  48.0

In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\User\Desktop\test_RTK1.txt",sep='\t')
df.head()

,Time_seconds,SatelliteID,C1C,L1C,D1C,S1C,C2L,L2L,D2L,S2L,C2S,L2S,D2S,S2S
0,15568,4,2.183553e+07,1.147465e+08,-2062.373,44.0,2.183554e+07,8.941286e+07,-1607.162,48.0,NaN,NaN,NaN,NaN
1,15568,7,2.403299e+07,1.262942e+08,1800.175,46.0,2.403299e+07,9.841108e+07,1402.741,43.0,NaN,NaN,NaN,NaN
2,15568,8,2.177553e+07,1.144312e+08,975.683,46.0,2.177553e+07,8.916716e+07,760.247,47.0,NaN,NaN,NaN,NaN
3,15568,9,2.159508e+07,1.134829e+08,541.655,49.0,2.159509e+07,8.842827e+07,421.945,48.0,NaN,NaN,NaN,NaN
4,15568,27,2.263255e+07,1.189348e+08,-1535.173,46.0,2.263256e+07,9.267653e+07,-1196.272,46.0,NaN,NaN,NaN,NaN

In [1]:
import gnss_lib_py as glp

In [6]:
from gnss_lib_py.parsers import rinex_obs  # or similar
from gnss_lib_py.parsers import rinex_nav  # or similar

# paths to your files
obs_path = r"F:\zizo\RTKCorrection\src\data\observation\20240214-041908.obs"
#nav_path = r"F:\zizo\RTKCorrection\src\data\navigation\Raw\RoverSt
# ationNav.nav"

lol = glp.RinexObs(obs_path)
lol

KeyboardInterrupt: